### PR TITLE
2K, 4K, 8K and 16K options for W5200

### PR DESCRIPTION
**Pull request by alex-Arc**
i have been using a 16k variant for close to a year now to receive 18 artnet universes at about 44 fps

### CODE REVIEW

**Comment by PaulStoffregen** [comment]
I'm planning to (eventually) make this a runtime configuration option, with an API for Arduino sketches to select the buffer size on a per-client basis.  That's why I haven't merged this...

**Comment by xseignard** [comment]
THat's a nice improvment I try to adapt for the W5500, so I tried to adapt the code, but I have then have a very slow perf.

I think I missed something, any idea on how to do the same for WS5500?

**Comment by xseignard** [comment]
I just tried the 16K option for the W5200 and it works great, I don't get why I cannot do the same for WS5500?

Regards

**Comment by alex-Arc** [comment]
have a look at this [https://github.com/alex-Arc/Ethernet/tree/Alternet_SPI_pin](url)

**Pull request closed without merging**
